version: '3.9'
services: 
    mysql_db_container:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        env_file:
          - ./config/mysql.env
        ports: 
          - 3307:3307
        volumes: 
            - mysql_db_data_container:/var/lib/mysql

    adminer_container:
        image: adminer:latest
        ports: 
          - 8080:8080

volumes: 
    mysql_db_data_container: 