version: '3.9'
services:
    database:
        image: db-mysql
        #command: --default-authentication-plugin=mysql_native_password
        container_name: db-mysql-container
        ports:
            - 3307:3307
        restart: always
        env_file:
            - ./config/mysql.env    
        volumes: 
            - db-mysql-volume:/var/lib/mysql
        networks:
            - db-mysql-volume-network        

    adminer_container:
        image: adminer:latest
        container_name: adminer-container
        restart: always
        ports: 
            - 8080:8080
        networks:
            - db-mysql-volume-network            

volumes: 
    db-mysql-volume: 

networks:
    db-mysql-volume-network:           